FROM ruby:3.3.5
RUN apt-get update -qq && apt-get install -y postgresql-client
WORKDIR /rails
COPY Gemfile Gemfile.lock ./
RUN bundle install
COPY . .
EXPOSE 3000
CMD ["bash", "-c", "rm -f tmp/pids/server.pid && ./bin/rails server -b 0.0.0.0"]
